name: steemdart_ecc
description: Elliptic curve cryptography functions in Dart. Private Key, Public Key, Signature, AES, Encryption, Decryption
version: 0.4.3
homepage: https://github.com/anpigon/steemdart_ecc

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  bs58check: ^1.0.1
  pointycastle: ^1.0.1
  crypto: ^2.1.5
  convert: ^2.1.1
  http: ^0.13.3

dev_dependencies:
  test: ^1.0.0
  dotenv: ^3.0.0
